"""Measure one product-intro video against a known bar grid (T04 checks).

Runs segments.py on the video, then reports what T04 makes claims about:
  - section boundaries (single transitions) and montage spans
  - lock of the boundaries to the bar grid and to the beat grid (phaselock.lock)
  - share of boundaries within +-100 ms of a bar line
  - section durations (median/min/max), first boundary, end-card hold
    (duration minus the last boundary or span end)
and writes measure.json + a 2 fps contact sheet for reading the headlines.

The bar grid comes from a truth JSON (make_beat_track.py output: bpm,
beats_per_bar, offset_s), so there is no downbeat ambiguity.

What it cannot determine: whether an event is a section change or a push-in /
modal inside a section (see segments.py); whether the film LOOKS like the cases.

Usage:
    python -X utf8 scripts/measure_product.py <final.mp4> --out <dir> --truth <beat json>
    python -X utf8 scripts/measure_product.py --aggregate "A=dirA1,dirA2,dirA3" "B=dirB1,..." --out table.md
    python -X utf8 scripts/measure_product.py --selftest
"""
import argparse
import json
import statistics as st
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import segments  # noqa: E402
from phaselock import lock  # noqa: E402


def grid_from_truth(truth):
    beat = 60.0 / truth["bpm"]
    return beat, beat * truth.get("beats_per_bar", 4), truth.get("offset_s", 0.0)


def measure(video, truth, min_cov=0.65):
    res, _, fps = segments.analyse(video, min_cov=min_cov)
    beat, bar, off = grid_from_truth(truth)
    trans = [e["t"] for e in res["events"] if e["kind"] == "transition"]
    spans = [(e["start"], e["end"]) for e in res["events"] if e["kind"] == "span"]
    # a transition whose run touches the film's first/last window (fade in from black, fade out at
    # the end) is not a section change; the run is truncated at the edge, so test the run, not t
    edge = res["params"]["w_s"] + 0.1
    trans_ev = [e for e in res["events"] if e["kind"] == "transition"]
    bounds = [e["t"] for e in trans_ev
              if e["t"] - e["run_s"] / 2 > edge and e["t"] + e["run_s"] / 2 < res["duration_s"] - edge]
    durs = [s["dur"] for s in res["sections"] if not s["montage"]]
    last = max([t for t in bounds] + [e for _, e in spans if e < res["duration_s"] - 0.5] or [0.0])
    near = [t for t in bounds if abs(((t - off + bar / 2) % bar) - bar / 2) <= 0.1]
    out = {
        "video": str(video), "duration_s": res["duration_s"], "fps": fps,
        "boundaries_s": bounds, "spans_s": spans, "n_boundaries": len(bounds), "n_spans": len(spans),
        "first_boundary_s": bounds[0] if bounds else None,
        "end_hold_s": round(res["duration_s"] - last, 3) if last else None,
        "section_dur_median_s": round(st.median(durs), 3) if durs else None,
        "section_dur_min_s": round(min(durs), 3) if durs else None,
        "section_dur_max_s": round(max(durs), 3) if durs else None,
        "bar_lock": lock(bounds, bar, off) if len(bounds) >= 2 else None,
        "beat_lock": lock(bounds, beat, off) if len(bounds) >= 2 else None,
        "share_within_100ms_of_bar": round(len(near) / len(bounds), 3) if bounds else None,
        "segments": res,
        "limits": "boundaries = segments.py single transitions; a push-in or modal also counts; "
                  "spans (montage) are not boundaries",
    }
    return out


def sheet(video, out_dir):
    subprocess.run([sys.executable, "-X", "utf8", str(Path(__file__).with_name("sheets.py")), str(video),
                    "--out", str(out_dir), "--fps", "2", "--cols", "8", "--rows", "6", "--thumb", "240"],
                   check=True, capture_output=True)


ROWS = [
    ("長度 s", "duration_s"), ("換段數", "n_boundaries"), ("連續變化區段數", "n_spans"),
    ("第一次換段 s", "first_boundary_s"), ("結尾停留 s", "end_hold_s"),
    ("段長中位數 s", "section_dur_median_s"), ("段長最短 s", "section_dur_min_s"),
    ("段長最長 s", "section_dur_max_s"), ("換段鎖小節 R", ("bar_lock", "R")),
    ("換段離小節線 ±100 ms 內的比例", "share_within_100ms_of_bar"), ("換段鎖拍點 R", ("beat_lock", "R")),
]


def pick(d, key):
    if isinstance(key, tuple):
        for k in key:
            d = d.get(k) if isinstance(d, dict) else None
        return d
    return d.get(key)


def aggregate(groups, out):
    lines = ["<!-- GENERATED by scripts/measure_product.py --aggregate; do not edit -->",
             "| 量測 | " + " | ".join(f"{g}（mean / min–max, n）" for g, _ in groups) + " |",
             "|---|" + "---|" * len(groups)]
    data = {g: [json.load(open(Path(d) / "measure.json", encoding="utf-8")) for d in dirs] for g, dirs in groups}
    for label, key in ROWS:
        cells = []
        for g, _ in groups:
            vals = [pick(m, key) for m in data[g]]
            vals = [v for v in vals if isinstance(v, (int, float))]
            cells.append(f"{st.mean(vals):.3g} / {min(vals):.3g}–{max(vals):.3g}, {len(vals)}" if vals else "—")
        lines.append(f"| {label} | " + " | ".join(cells) + " |")
    lines.append("")
    for g, dirs in groups:
        for d, m in zip(dirs, data[g]):
            lines.append(f"- {g} `{d}`: boundaries {m['boundaries_s']}; spans {m['spans_s']}")
    Path(out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


def synth_edges(path, dur=8.0):
    """Fade in from black over 0-0.5 s, a hard cut at 4.0 s, fade out to black over 7.5-8.0 s."""
    fps = segments.FPS
    n = int(dur * fps)
    vid = np.zeros((n, segments.H, segments.W), np.uint8)
    for i in range(n):
        t = i / fps
        f = segments.local_motion(segments.layout(0 if t < 4.0 else 1), t).astype(float)
        k = min(1.0, t / 0.5, max(0.0, (dur - t) / 0.5))
        vid[i] = np.clip(f * k, 0, 255).astype(np.uint8)
    segments._encode(vid, path)


def selftest():
    ok = True
    truth = {"bpm": 120.0, "beats_per_bar": 4, "offset_s": 0.0}
    with tempfile.TemporaryDirectory() as td:
        p = Path(td) / "on.mp4"
        want = segments.synth_sections(p, scale=0.8)          # transitions at 2, 4, 6, 8 s = bar lines
        m = measure(p, truth)
        good = (m["bar_lock"] and m["bar_lock"]["R"] > 0.95 and m["share_within_100ms_of_bar"] == 1.0
                and m["n_boundaries"] == 4)
        print(f"known-true (boundaries {want} on 2 s bars): got {m['boundaries_s']}, bar R "
              f"{m['bar_lock'] and m['bar_lock']['R']}, within 100 ms {m['share_within_100ms_of_bar']} "
              f"-> {'ok' if good else 'FAIL'}")
        ok &= good
        q = Path(td) / "off.mp4"
        want = segments.synth_sections(q, scale=1.0)          # 2.5, 5, 7.5, 10: quarter-bar apart on the cycle
        m = measure(q, truth)
        good = m["bar_lock"] and m["bar_lock"]["R"] < 0.3 and m["share_within_100ms_of_bar"] <= 0.25
        print(f"known-false (boundaries {want}, spread over the bar): bar R {m['bar_lock'] and m['bar_lock']['R']}, "
              f"within 100 ms {m['share_within_100ms_of_bar']} -> {'ok' if good else 'FAIL'}")
        ok &= good
        good = m["end_hold_s"] is not None and abs(m["end_hold_s"] - (12.0 - 10.0)) <= 0.1
        print(f"end hold after the last transition (want 2.0 s): {m['end_hold_s']} -> {'ok' if good else 'FAIL'}")
        ok &= good
        r = Path(td) / "edges.mp4"
        synth_edges(r)
        m = measure(r, truth)
        good = m["boundaries_s"] == [4.0] or (len(m["boundaries_s"]) == 1 and abs(m["boundaries_s"][0] - 4.0) <= 0.1)
        good = good and m["end_hold_s"] is not None and abs(m["end_hold_s"] - 4.0) <= 0.1
        print(f"known-false edges (fade in from black 0-0.5 s, fade out 7.5-8 s, one cut at 4.0): boundaries "
              f"{m['boundaries_s']} want [4.0], end hold {m['end_hold_s']} want 4.0 -> {'ok' if good else 'FAIL'}")
        ok &= good
    print("SELFTEST", "PASS" if ok else "FAIL")
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("video", nargs="?")
    ap.add_argument("--out")
    ap.add_argument("--truth")
    ap.add_argument("--aggregate", nargs="+", help='"NAME=dir,dir" ...')
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        sys.exit(selftest())
    if a.aggregate:
        groups = [(g.split("=", 1)[0], g.split("=", 1)[1].split(",")) for g in a.aggregate]
        aggregate(groups, a.out)
        return
    truth = json.load(open(a.truth, encoding="utf-8"))
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    m = measure(a.video, truth)
    (out / "measure.json").write_text(json.dumps(m, indent=1, ensure_ascii=False), encoding="utf-8")
    sheet(a.video, out / "sheets")
    print(json.dumps({k: m[k] for k in m if k not in ("segments",)}, ensure_ascii=False))


if __name__ == "__main__":
    main()
